version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DATABASE_NAME=connect-four"
      - "DATABASE_USERNAME=postgres"
      - "DATABASE_PASSWORD=postgres"
      - "DATABASE_HOST=database"
      - "DATABASE_PORT=5432"
    ports:
      - "5000:5000"
    links:
      - game-server-db

  database:
    image: postgres:12
    environment:
      - "POSTGRES_DB=connect-four"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_PASSWORD=postgres"
    expose:
      - "5432"